---
sidebar: sidebar 
permalink: faq-cloud-compliance.html 
keywords: faq, frequently asked questions, questions, cloud compliance, data sense 
summary: 如果您只是想快速找到問題的答案，此常見問題解答可以為您提供協助。 
---
= 關於NetApp資料分類的常見問題解答
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您只是想快速找到問題的答案，此常見問題解答可以為您提供協助。



== NetApp資料分類

以下問題提供了對資料分類的一般了解。



=== 資料分類如何運作？

資料分類在NetApp控制台系統和儲存系統旁邊部署了另一層 AI。然後，它會掃描磁碟區、儲存桶、資料庫和其他儲存帳戶上的數據，並對找到的數據洞察進行索引。資料分類利用人工智慧和自然語言處理，而不是通常圍繞正規表示式和模式匹配構建的替代解決方案。

資料分類使用人工智慧來提供對資料的上下文理解，以便進行準確的檢測和分類。它由人工智慧驅動，因為它是針對現代資料類型和規模而設計的。它還了解數據背景，以便提供強大、準確的發現和分類。

link:concept-classification.html["詳細了解資料分類的工作原理"] 。



=== 資料分類是否有 REST API，它是否可以與第三方工具一起使用？

是的，資料分類有一個 REST API，用於支援控制台核心平台一部分的資料分類版本中的功能。看link:api-classification.html["API 文件"] 。



=== 資料分類是否可以透過雲端市場取得？

資料分類是NetApp控制台核心功能的一部分，因此您不需要使用此服務的市場。



== 資料分類掃描與分析

以下問題與資料分類掃描效能和分析有關。



=== 資料分類多久掃描一次我的資料？

雖然初始資料掃描可能需要一點時間，但後續掃描僅檢查增量變化，從而減少系統掃描時間。資料分類以循環方式連續掃描您的數據，每次掃描六個儲存庫，以便所有更改的資料都能快速分類。

link:task-scanning-overview.html["了解掃描的工作原理"] 。

資料分類每天僅掃描資料庫一次；資料庫不像其他資料來源那樣被連續掃描。

資料掃描對您的儲存系統和資料的影響可以忽略不計。



=== 掃描性能是否有所不同？

掃描效能可能會因網路頻寬和環境中的平均檔案大小而異。它還取決於主機系統（在雲端或本地）的大小特徵。請參閱link:concept-classification.html["資料分類實例"]和link:task-deploy-overview.html["部署資料分類"]了解更多。

在最初新增的資料來源時，您也可以選擇僅執行「對應」（Mapping only）掃描，而不是完整的「分類」（Map & Classify）掃描。由於它不需要存取檔案來查看其中的數據，因此可以非常快速地在資料來源上完成映射。link:task-scanning-overview.html["查看映射和分類掃描之間的區別"] 。



=== 我可以使用資料分類搜尋我的資料嗎？

資料分類提供了廣泛的搜尋功能，可以輕鬆地在所有連接的來源中搜尋特定檔案或資料。資料分類使用戶能夠進行比元資料所反映的更深入的搜尋。它是一種與語言無關的服務，還可以讀取檔案並分析多種敏感資料類型，例如名稱和 ID。例如，使用者可以在結構化和非結構化資料儲存中進行搜索，以查找可能從資料庫洩漏到使用者文件的數據，從而違反公司政策。可以儲存搜尋結果以供日後使用，並且可以建立策略以設定的頻率搜尋並對結果採取行動。

一旦找到感興趣的文件，就可以列出其特徵，包括標籤、系統帳戶、儲存桶、文件路徑、類別（來自分類）、文件大小、上次修改、權限狀態、重複、敏感度等級、個人資料、文件內的敏感資料類型、擁有者、文件類型、文件大小、建立時間、文件雜湊、資料是否分配給尋求其關注的人等等。可以使用過濾器來篩選出不相關的特徵。

如果存在正確的權限，資料分類還具有基於角色的存取控制（RBAC），允許移動或刪除檔案。如果沒有正確的權限，則可以將任務指派給組織中具有正確權限的人員。



== 資料分類管理和隱私

以下問題提供了有關如何管理資料分類和隱私設定的資訊。



=== 如何啟用或停用資料分類？

首先，您需要在控制台或本機系統中部署資料分類實例。執行個體執行後，您可以從「配置」標籤或透過選擇特定係統在現有系統、資料庫和其他資料來源上啟用服務。link:task-getting-started-compliance.html["了解如何開始"] 。


NOTE: 在資料來源上啟動資料分類將立即導致初始掃描。掃描結果很快就會顯示。

您可以從資料分類設定頁面停用資料分類掃描單一系統、資料庫或檔案共用群組。看link:task-managing-compliance.html["從資料分類中刪除資料來源"] 。

若要完全刪除資料分類實例，請從雲端提供者的入口網站或本機位置手動刪除資料分類實例。



=== 該服務可以排除某些目錄中的掃描資料嗎？

是的。如果您希望資料分類排除駐留在特定資料來源目錄中的掃描數據，則可以將該清單提供給分類引擎。套用變更後，資料分類將排除指定目錄中的掃描資料。link:task-exclude-scan-paths.html["了解更多"] 。



=== 是否掃描了位於ONTAP磁碟區上的快照？

否。資料分類不會掃描快照，因為其內容與磁碟區中的內容相同。



=== 如果在ONTAP磁碟區上啟用了資料分層，會發生什麼情況？

當資料分類使用僅映射掃描掃描具有分層到物件儲存的冷資料的磁碟區時，它會掃描所有資料 - 本地磁碟上的資料和分層到物件儲存的冷資料。對於實施分層的非NetApp產品也是如此。

僅映射掃描不會使冷資料升溫—它會保持冷狀態並保留在物件儲存中。另一方面，如果您執行地圖和分類掃描，某些配置可能會使冷資料升溫。



== 來源系統和資料類型的類型

以下問題涉及可掃描的儲存類型以及掃描的資料類型。



=== 在政府區域部署時有限制嗎？

當控制台代理部署在政府區域（AWS GovCloud、Azure Gov 或 Azure DoD）時，支援資料分類 - 也稱為「受限模式」。



=== 如果我在沒有網路存取的網站安裝資料分類，我可以掃描哪些資料來源？


IMPORTANT: BlueXP私有模式（傳統BlueXP介面）通常用於沒有網路連線的本機環境和安全雲端區域，其中包括 AWS Secret Cloud、AWS Top Secret Cloud 和 Azure IL6。NetApp繼續透過傳統的BlueXP介面支援這些環境。有關舊版BlueXP介面中的私有模式文檔，請參閱link:https://docs.netapp.com/us-en/console-setup-admin/media/BlueXP-Private-Mode-legacy-interface.pdf["BlueXP私人模式的 PDF 文檔"^]。

資料分類只能掃描來自本地站點的資料來源的資料。目前，資料分類可以以「私人模式」掃描以下本地資料來源 - 也稱為「暗」網站：

* 本地ONTAP系統
* 資料庫模式
* 使用簡單存儲服務（S3）協定的對象存儲




=== 支援哪些文件類型？

資料分類掃描所有文件的類別和元資料洞察，並在儀表板的文件類型部分顯示所有文件類型。

當資料分類偵測到個人識別資訊 (PII) 或執行 DSAR 搜尋時，僅支援以下文件格式：

`+.CSV, .DCM, .DOC, .DOCX, .JSON, .PDF, .PPTX, .RTF, .TXT, .XLS, .XLSX, Docs, Sheets, and Slides+`



=== 資料分類擷取哪些類型的資料和元資料？

資料分類可讓您對資料來源執行常規「映射」掃描或完整「分類」掃描。映射僅提供資料的高級概述，而分類提供資料的深層掃描。由於它不需要存取檔案來查看其中的數據，因此可以非常快速地在資料來源上完成映射。

* *資料映射掃描（僅映射掃描）*：資料分類僅掃描元資料。這對於整體資料管理和治理、快速專案範圍界定、大型地產和優先排序很有用。數據映射基於元數據，被認為是一種*快速*掃描。
+
快速掃描後，您可以產生資料映射報告。此報告概述了您公司資料來源中儲存的數據，以幫助您做出有關資源利用率、遷移、備份、安全性和合規性流程的決策。

* *資料分類深度掃描（地圖和分類掃描）*：資料分類使用標準協定和唯讀權限在整個環境中掃描資料。開啟選定的文件並掃描其中的敏感業務相關資料、私人資訊以及與勒索軟體相關的問題。
+
完整掃描後，您可以將許多附加資料分類功能套用至數據，例如在資料調查頁面中查看和最佳化資料、在檔案中搜尋名稱、複製、移動和刪除來源檔案等。



資料分類擷取元數據，例如：檔案名稱、權限、建立時間、上次存取和上次修改。這包括資料調查詳情頁面和資料調查報告中顯示的所有元資料。

資料分類可以識別多種類型的私人數據，例如個人資訊（PII）和敏感個人資訊（SPII）。有關私人數據的詳細信息，請參閱 https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html["資料分類掃描的私人資料類別"]。



=== 我可以將資料分類資訊限制給特定使用者嗎？

是的，資料分類與NetApp控制台完全整合。  NetApp控制台使用者只能查看根據其權限有資格查看的系統的資訊。

此外，如果您希望允許某些使用者僅查看資料分類掃描結果而無權管理資料分類設置，則可以為這些使用者指派*分類檢視器*角色（在標準模式下使用NetApp控制台時）或*合規性檢視器*角色（在受限模式下使用NetApp控制台時）。link:concept-classification.html["了解更多"] 。



=== 任何人都可以存取我的瀏覽器和資料分類之間發送的私人資料嗎？

不可以。您的瀏覽器和資料分類實例之間發送的私人資料使用 TLS 1.2 進行端對端加密保護，這表示NetApp和非NetApp方都無法讀取它。除非您要求並批准訪問，否則資料分類不會與NetApp共用任何資料或結果。

掃描的資料保留在您的環境中。



=== 敏感資料如何處理？

NetApp無法存取敏感數據，也不會在 UI 中顯示它。敏感資料被封鎖，例如，顯示信用卡資訊的最後四位數字。



=== 資料儲存在哪裡？

掃描結果儲存在資料分類實例內的 Elasticsearch 中。



=== 如何存取資料？

資料分類透過 API 呼叫存取儲存在 Elasticsearch 中的數據，這些呼叫需要身份驗證並使用 AES-128 加密。直接存取 Elasticsearch 需要 root 存取權限。



== 許可證和費用

以下問題涉及使用資料分類的許可和成本。



=== 資料分類的費用是多少？

資料分類是NetApp控制台的核心功能。沒有扣費。



== 控制台代理部署

以下問題與控制台代理有關。



=== 什麼是控制台代理？

控制台代理程式是在您的雲端帳戶或本機的運算實例上執行的軟體，它使NetApp控制台能夠安全地管理雲端資源。您必須部署控制台代理程式才能使用資料分類。



=== 控制台代理需要安裝在哪裡？

掃描資料時，需要在以下位置安裝NetApp Console 代理程式：

* 對於 AWS 中的Cloud Volumes ONTAP或Amazon FSx for ONTAP：控制台代理程式位於 AWS 中。
* 對於 Azure 或Azure NetApp Files中的Cloud Volumes ONTAP ：控制台代理程式位於 Azure 中。
* 對於 GCP 中的Cloud Volumes ONTAP ：控制台代理程式位於 GCP 中。
* 對於本機ONTAP系統：控制台代理程式位於本機。


如果您在這些位置有數據，您可能需要使用 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html#when-to-use-multiple-connectors["多個控制台代理"^]。



=== 資料分類是否需要存取憑證？

資料分類本身不會檢索儲存憑證。相反，它們存儲在控制台代理中。

資料分類使用資料平面憑證（例如 CIFS 憑證）在掃描之前掛載共用。



=== 服務和控制台代理之間的通訊是否使用 HTTP？

是的，資料分類使用 HTTP 與控制台代理進行通訊。



== 資料分類部署

以下問題與單獨的資料分類實例有關。



=== 資料分類支援哪些部署模型？

NetApp控制台允許使用者在幾乎任何地方掃描和報告系統，包括本機、雲端和混合環境。資料分類通常使用 SaaS 模型部署，其中服務透過控制台介面啟用，不需要安裝硬體或軟體。即使在這種點擊即運行的部署模式下，無論資料儲存是在本地還是在公有雲中，都可以進行資料管理。



=== 資料分類需要什麼類型的實例或虛擬機器？

什麼時候link:task-deploy-cloud-compliance.html["部署在雲端"]：

* 在 AWS 中，資料分類在具有 500 GiB GP2 磁碟的 m6i.4xlarge 執行個體上執行。您可以在部署期間選擇較小的實例類型。
* 在 Azure 中，資料分類在具有 500 GiB 磁碟的 Standard_D16s_v3 VM 上執行。
* 在 GCP 中，資料分類在具有 500 GiB 標準持久磁碟的 n2-standard-16 VM 上運作。


link:concept-classification.html["詳細了解資料分類的工作原理"] 。



=== 我可以在自己的主機上部署資料分類嗎？

是的。您可以在網路或雲端中具有網際網路存取權限的 Linux 主機上安裝資料分類軟體。一切運作相同，您可以繼續透過控制台管理掃描配置和結果。看link:task-deploy-compliance-onprem.html["在本地部署資料分類"]了解系統需求和安裝詳情。



=== 沒有網路連線的安全站點怎麼樣？

是的，也支持。你可以link:task-deploy-compliance-dark-site.html["在沒有網路存取權限的本機站點中部署資料分類"]以獲得完全安全的網站。
