---
sidebar: sidebar 
permalink: task-deploy-overview.html 
keywords: cloud compliance, data sense, get started, deploy cloud data sense, outbound internet, endpoints, cloud compliance internet, web browser connectivity, cloud compliance access, privacy, compliance, bluexp classification 
summary: 規劃哪種NetApp Data Classification部署可以滿足您的需求。 
---
= NetApp Data Classification 部署方法
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp 資料分類支援多種部署方式，以滿足不同的網路和連線需求。請查看可用方法，選擇最適合您環境的選項。

* link:task-deploy-cloud-compliance.html["使用控制台在雲端部署"] 。控制台將資料分類執行個體部署在與控制台代理相同的雲端提供者網路中。
* link:task-deploy-compliance-onprem.html["在可以存取網際網路的 Linux 主機上安裝"]。在網路或雲端的 Linux 主機上安裝 NetApp Data Classification。如果您希望從位於內部部署的 NetApp Data Classification 執行個體掃描內部部署的 ONTAP 系統，此選項可能很有用，但並非必須將執行個體放置在內部部署環境中。
* link:task-deploy-compliance-dark-site.html["在沒有網際網路存取的本機站點的 Linux 主機上安裝"]，稱為「私有模式」。這種安裝方式使用安裝指令碼，與 Console SaaS 階層沒有連線。



TIP: 對於內部部署 VMware vSphere 部署、Data Classification 支援簡化的link:task-deploy-ova.html["使用 OVA 進行部署"]。



[[on-premises-installation-script]]
== 內部部署安裝指令碼

兩種安裝方法都使用安裝指令碼。此指令碼會檢查系統和環境是否符合先決條件。如果符合，則開始安裝。

有個獨立的軟體套件可用於驗證您的 Linux 主機是否已準備就緒。若要執行驗證套件，請參閱link:task-test-linux-system.html["請確認您的 Linux 主機已準備好安裝 Data Classification"]。
